### PR TITLE
Dedicated Thread

### PR DESCRIPTION
**Pull request by friedger**
This PR
* uses a dedicated thread for all calls to the Android Blockstack SDK
* improves the example
* uses the Android blockstack sdk directly from local folder (developers need to checkout blockstack-android)
* adds RNMethods `isUserSignedIn`, `loadUserData`
* upgrades tools

To test in Android Studio
1. checkout feature/threadlock
1. open folder `example-sdk-module/android` in Android Studio
1. open terminal, `cd ..` 
1. run react-native start
1. open second terminal, `adb reverse tcp:8081 tcp:8081`
1. launch `app` in Android Studio

### CODE REVIEW

**Comment by friedger** [comment]
Use `run-android` instead of `start`

**Comment by larrysalibra** [comment]
When I use 'run-android' it gives me an error because I don't have Oracle's java installed - only the java bundled with android studio. Last time I was able to test the react-native example app by running it from the command line as above. Any other ideas I should try?

**Comment by clydedacruz** [comment]
@larrysalibra  @friedger  the sequence which usually works for me is, 
1. Make sure you have a device running, using `adb devices` , and make sure your `ANDROID_HOME` is set to the sdk location.
2. `npm install`
3. Start packager server `npm start`. May sometimes need to do `npm start --reset-cache`
Now check if the packager server is really running on the default port i.e localhost:8081
Wait till it shows a message like `Loading dependency graph, done.`

2. In a different terminal do `react-native run-android`

**Comment by friedger** [comment]
@larrysalibra Maybe try `adb reverse tcp:8081 tcp:8081`. I have updated the description of this PR to include the steps to verify the code.

**Comment by shreyasthiagaraj** [comment]
Looks good to me @friedger, thanks for your help in understanding it. I've merged it in.

**Pull request merged**
