### PR TITLE
added encryptContent, decryptContent to android native module

### PR DESCRIPTION
**Pull request by clydedacruz**
Added `encryptContent` , `decryptContent` functions to android native module
Updated app.js to test encryption, decryption with app keys and with user-provided keys

### CODE REVIEW

**Comment by friedger** [comment]
Nice!
Just two comments:
* Your PR also contains gradle files, does it work for you? I haven't figured out the best way to set this up in Android Studio.
* And the app would fail on iOS. Can you please add a check for Android environment?

**Comment by clydedacruz** [comment]
@friedger 
Added the check for platform

It works for me in Android studio without any problems.
The steps I follow are below
Cheers!


**Clone code**
```
clone git@github.com:clydedacruz/blockstack-react-native.git
cd example-sdk-module
npm install 
```
**Open project** 
In android studio, go to _File> open > blockstack-react-native > example-sdk-module > android_
Let sync complete.

After app has installed on device, it will show the red screen complaining it cant connect to the package manager

**Use `adb reverse` to access packager running on localhost**
```
adb reverse tcp:8081 tcp:8081
```
**start packager**
```
react-native start 
```
Now hit reload on the app error screen

**Comment by clydedacruz** [comment]
@friedger  @shreyasthiagaraj  please verify and merge if all good.
Thanks :)

**Comment by friedger** [comment]
@clydedacruz You still have the gradle stuff in the android directory. It is already contained in the root directory. I don't think we need it at both places.

**Comment by friedger** [comment]
Let's move towards an independent android setup for the sdk and the example.
I'll merge this PR and then remove the gradle files from the root directory.

**Pull request merged**
